Task4 # Components (Part 2)
akuchynski/movies-spa pull request #3
Opened 2021-10-05 15:58 UTC by akuchynski

Task4:

- Styles and markup are implemented
- Used stateless/stateful approach
- Used event handlers
- Use lifecycle methods or useEffect hook

2021-10-05 19:38 UTC, yugako requested changes

2021-10-05 19:38 UTC, yugako commented on src/components/modal/DeleteMovie.js
> +        const checkClick = e => {
Дублюєш той самий код тут і в `MoviewModal`. Ось це якраз хороший кандидат на кастомний хук.

2021-10-05 19:38 UTC, yugako commented on src/components/modal/MovieModal.js
> +                    <label className="modal-text">
Щоб не писати багато розмітки, можеш конфіг для інпутів зробити і просто через `map` то все вивести. Акуратніше виглядати буде

2021-10-05 19:38 UTC, yugako commented on src/components/modal/MovieModal.js
> +            }
І ще слідкуй за пунктуацією і не забувай крапки з комою ставити в кінці конструкцій

2021-10-05 19:38 UTC, yugako commented on src/components/Movie/MovieItem.js
> +                        <li><a href="#" onClick={handleDeleteModal}>DELETE</a></li>
Як на мене, тег `a` тут семантично не дуже підходить, але це не критично, може бути і так

2021-10-05 19:38 UTC, yugako commented on src/components/Movie/MovieItem.js
> +            <div className="movie-info">
Також я б трохи перегрупував верстку, попапи, наприклад, пересунув вниз, а контент який безпосередньо відповідає за відображення одного фільму згрупував би разом

2021-10-06 15:45 UTC, akuchynski commented on src/components/Movie/MovieItem.js
> +            <div className="movie-info">
done

2021-10-12 09:57 UTC, merged